---
title: "CITS4009 Project 1 — Exploratory Data Analysis"
output: html_document
date: "2023-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Including Plots

```{r}
library(datasets)
#install.packages("ggplot2")
#head(iris)
#getwd()
setwd("/home/saraj/Desktop/Data_Analytics")
#print(5)
data_ <- read.csv('Global YouTube Statistics.csv')
#print(data)

### Summary of datasset
summary(data_)

### Str() to display the structures of dataset
str(data_)

### head() to display the first n rows present in the input data frame, by default 6
head(data_)

#plot(data)
library(ggplot2)
library("dplyr")
library(plyr)


#data_grp <- group_by("category")
#ggplot2(data)
################################## Youtubers based on Categories #############################################
categories <- unique(data_$category)
data_cnt <-count(data_, "category")
#print(data_cnt)
freq <- data_cnt["freq"]
category = data_cnt["category"]
#print(freq)
#print(category)
length(category) == length(freq)
#print(freq)
#print(category)

 
### Bar Chart of Category wise grouping
ggplot(data_cnt, mapping = aes(x = category, y = freq), col='blue') +
  geom_bar(stat='identity')


### Scatter plot representation of Category wise grouping
ggplot(data_cnt, mapping = aes(x = category, y = freq)) +
  geom_point()

## Colorful Points
ggplot(data_cnt, mapping = aes(x = category, y = freq)) +
 geom_point(color = "blue") + geom_smooth(color = "red")

#ggplot(data_cnt, mapping = aes(x = category, y = freq)) +
#stat_summary(fun = "mean", geom = "line", linetype = "dashed")

## Histogram
ggplot(data_cnt, mapping = aes(x = category, y = freq)) +
  geom_histogram(stat='identity', color="red") + coord_polar()

#print(categories)


################################## Youtubers based on Country #############################################


Countries <- unique(data_$Country)
country_cnt <-count(data_, "Country")
#print(country_cnt)
freq <- country_cnt["freq"]
country = country_cnt["Country"]
#print(freq)
#print(country)
length(country) == length(freq)
#print(freq)
#print(country)
#data_cnt


### Bar Chart of Category wise grouping
ggplot(country_cnt, mapping = aes(x = Country, y = freq), col='blue') +
  geom_bar(stat='identity')


### Scatter plot representation of Category wise grouping
ggplot(country_cnt, mapping = aes(x = Country, y = freq)) +
  geom_point()

## Colorful Points
ggplot(country_cnt, mapping = aes(x = Country , y = freq)) +
  geom_point(color = "blue") + geom_smooth(color = "red")

#ggplot(data_cnt, mapping = aes(x = category, y = freq)) +
#stat_summary(fun = "mean", geom = "line", linetype = "dashed")

## Histogram
ggplot(country_cnt, mapping = aes(x = Country, y = freq)) +
  geom_histogram(stat='identity', color="red") + coord_polar()



#PieChart
piepercent<- round(100*country_cnt$freq/sum(country_cnt$freq), 1)
pie(country_cnt$freq, piepercent, col = rainbow(length(country_cnt$Country)))
legend("topright", country_cnt$Country,
fill = rainbow(length(country_cnt$freq)))
print(categories)

##Piechart2
piepercent<- round(100*country_cnt$freq/sum(country_cnt$freq), 1)

pie(country_cnt$freq, country_cnt$Country,main="Youtubers based on Countries", col = rainbow(length(country_cnt$Country)))


############ Earning Based on Subscribers and Uploads  ########################


h = head(data_, 200)
#print(h)

if (!requireNamespace("scatterplot3d", quietly = TRUE)) {
  install.packages("scatterplot3d")
}
library(scatterplot3d)

# Load the iris dataset
data("iris")

# Create a 3D scatter plot
scatterplot3d(h$subscribers, h$uploads, h$highest_yearly_earnings,
              color = h$rank, pch = 25, type="h", 
              main = "Yearly Earnings based on Subscribers and Uploads",
              xlab = "Subscribers", ylab = "Uploads", zlab = "Highest_yearly_earnings")


############################# Linear Regression ##################################


# Visualising the Training set results
#install.packages("ggplot2")
library(ggplot2)

lm.r = lm(formula =highest_yearly_earnings  ~ video.views, data= data_)
ggplot() + geom_point(aes(x = data_$video.views,
                          y = data_$highest_yearly_earnings), colour = 'red') +
  geom_line(aes(x = data_$video.views,
                y = predict(lm.r, newdata = data_)), colour = 'blue') +
  
  ggtitle('Subcribers Vs Yearly_Earnings') +
  xlab('Video Views') +
  ylab('Lowest_yearly_earnings')


```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
